chore: test discrod notifications !ignore

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -2,6 +2,8 @@ name: Build
 
 on: [push, pull_request]
 
+
+
 jobs:
   triage-labels:
     name: Add labels
@@ -77,7 +79,7 @@ jobs:
       run: npm ci
 
     - name: Build
-      run: npm run build
+      run: npm run build && exit 1
 
   coverage:
     name: Coverage
@@ -123,57 +125,46 @@ jobs:
         token: ${{ secrets.CODECOV_TOKEN }}
         file: ./coverage/lcov.info
 
-  one:
+  discord:
+    name: Discord notification
+    needs: [test, build, coverage]
+    if: ${{ always() }}
     runs-on: ubuntu-latest
-    needs: [build]
+    env:
+      DISCORD_USERNAME: github
+      DISCORD_ERROR_COLOR: 16726645
+      DISCORD_ERROR_AVATAR: https://cdn.jsdelivr.net/gh/tagproject/art/bot/bot-error.png
+      DISCORD_EVENT_COLOR: 53759
+      DISCORD_EVENT_AVATAR: https://cdn.jsdelivr.net/gh/tagproject/art/bot/bot-event.png
+      DISCORD_SUCCESS_COLOR: 969384
+      DISCORD_SUCCESS_AVATAR: https://cdn.jsdelivr.net/gh/tagproject/art/bot/bot-success.png
     steps:
-    - name: Dump GitHub context
-      env:
-        GITHUB_CONTEXT: ${{ toJSON(github) }}
-      run: echo "$GITHUB_CONTEXT"
-    - name: Dump job context
-      env:
-        JOB_CONTEXT: ${{ toJSON(job) }}
-      run: echo "$JOB_CONTEXT"
-    - name: Dump steps context
-      env:
-        STEPS_CONTEXT: ${{ toJSON(steps) }}
-      run: echo "$STEPS_CONTEXT"
-    - name: Dump runner context
-      env:
-        RUNNER_CONTEXT: ${{ toJSON(runner) }}
-      run: echo "$RUNNER_CONTEXT"
-    - name: Dump strategy context
-      env:
-        STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
-      run: echo "$STRATEGY_CONTEXT"
-    - name: Dump matrix context
-      env:
-        MATRIX_CONTEXT: ${{ toJSON(matrix) }}
-      run: echo "$MATRIX_CONTEXT"
+    - name: Send error notification after push commit
+      if: ${{ contains(needs.*.result, 'failure') && github.event_name == 'push' }}
+      uses: sarisia/actions-status-discord@v1
+      with:
+        webhook: ${{ secrets.DISCORD_WEBHOOK }}
+        nodetail: true
+        username: ${{ env.DISCORD_USERNAME }}
+        avatar_url: ${{ env.DISCORD_ERROR_AVATAR }}
+        title: 'Build for [commit](${{ github.event.head_commit.url }}) is failed :confused:'
+        color: ${{ env.DISCORD_ERROR_COLOR }}
+        description: |
+          **Repository:** `${{ github.repository }}`
+          **Branch:** `${{ github.event.ref }}`
+          **Author:** [${{ github.event.head_commit.author.username }}](https://github.com/${{ github.event.head_commit.author.username }})
 
-#  discord-error:
-#    name: Discord error notification
-#    if: ${{ failure() }}
-#    needs: [build, coverage]
-#    runs-on: ubuntu-latest
-#    steps:
-#    - name: Discord error notification
-#      env:
-#        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
-#        DISCORD_AVATAR: https://cdn.jsdelivr.net/gh/tagproject/art/bot/bot-error.png
-#        DISCORD_EMBEDS: ${{ toJson(my_value) }}
-#      uses: Ilshidur/action-discord@master
-#      with:
-#        args: 'Build [here](${{  }})'
+
+
+
+
+
+
 #https://github.com/marketplace/actions/actions-status-discord
 #https://convertingcolors.com/hex-color-0ECAA8.html?search=#0ECAA8
 
-
-
-
-
-
+# https://github.community/t/run-next-job-sequentially-even-if-a-previous-job-fails/17404/2
 
 # https://github.com/keindev/changelog-guru/runs/2242003345?check_suite_focus=true
+# https://github.com/keindev/changelog-guru/runs/2242060706?check_suite_focus=true
 
